# Generated by Django 2.2.4 on 2019-08-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('is_available', models.BooleanField(default=True)),
                ('is_promoted', models.BooleanField(default=False)),
            ],
        ),
    ]
